Fix pre-push script

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -1,23 +1,24 @@
 #!/bin/sh
 #!/usr/bin/env bash
 
+exit=0
 echo "Running ruff check..."
-if ! ruff check --extend-select I --fix --exit-zero
+if ! ruff check --extend-select I --fix
 then
-    echo "ruff check failed."
-    exit 1
+    exit=1
 fi
 
 echo "Running ruff format..."
 if ! ruff format --check --target-version py312 --quiet
 then
+    exit=1
     ruff format --target-version py312
-    # Currently, we cant distinguish between formatting errors and actual ruff internal errors, so we just run the check again
-    if ruff format --check --target-version py312 --quiet
-    then
-        echo "ruff format failed."
-        exit 1
-    fi
+fi
+
+if [ $exit -ne 0 ]
+then
+    echo "ruff checks or formatting failed."
+    exit 1
 fi
 
 echo "ruff checks and formatting completed successfully."
